### PR TITLE
update gems (ruby2.1.5 and rails4.2.0.rc3) and add test

### PR DESCRIPTION
**Pull request by t-jindai**
@smidwap 

Thank you for your great sample for Ruby on Rails using TodoMVC.
It is good sample to learn RoR.

I also want to support to learn RoR for someone who start studying RoR.
So I updated gem (ruby -> 2.1.5 and rails -> 4.2.0.rc3) and added rspecs.

If you don't mind please merge it.
## how to test

```
cd todomvc_on_rails
```

add qt for capybara-webkit

``` bash
brew install qt
```

update gems

``` bash
bundle update
```

execute test

```
rspec spec
```

### CODE REVIEW

**Comment by kashiro** [comment]
@smidwap 

Long time no see :)
how was this ?

**Comment by smidwap** [comment]
Hey @kashiro 

Really sorry about this. No excuses for the delay.

Unfortunately I don't want to merge this. Adding tests is a good idea, but I'm not interested in having this repository be anything but *my* simple version of the TodoMVC on Rails. I'm also not familiar with Capybara, and FactoryGirl/rspec wouldn't be my first choice for testing.

But it might be useful for some to see tests. So, if you fork this project, I'd be happy to link to it on the Readme. What do you say?

Thanks again for taking the time to do this. It was cool to see how Capybara worked.

**Comment by kashiro** [comment]
@smidwap Thank you for your concern :) 

I forked your repository.
I'm happy if this code help someone !

https://github.com/kashiro/todomvc_on_rails_with_test

**Comment by smidwap** [comment]
@kashiro Thanks for this! I've updated the readme with a link to your fork: https://github.com/smidwap/todomvc_on_rails/blob/master/README.rdoc

**Pull request closed without merging**
